version: '3.8'
services:
  db:
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_DB: guess_country
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: server
    build: ./server   # Specify the build context for the backend (server)
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./server/.env  # Adjust the path to your .env file
  client:
    container_name: client
    build: ./client   # Specify the build context for the frontend (client)
    ports:
      - "3000:80"  # Expose the frontend on port 3000
    depends_on:
      - server        # Ensure the client waits for the backend to be available

