version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Your NGINX configuration
      - /etc/ssl/certs:/etc/ssl/certs:ro  # Mount the SSL certs directory
    depends_on:
      - frontend
      - backend
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6351:6333
      - 6352:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./databases/qdrant/snapshots:/qdrant/snapshots
      - ./qdrant_data:/qdrant/storage
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: database
    build:
      context: ./databases/postgres
    environment:
      POSTGRES_DB: guess_country
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./databases/postgres/init.sql:/docker-entrypoint-initdb.d/a_init.sql
      - ./databases/postgres/countries_dump.sql:/docker-entrypoint-initdb.d/countries_dump_countries.sql
      - ./databases/postgres/countries_dump_docs.sql:/docker-entrypoint-initdb.d/countries_dump_docs.sql
      - ./databases/postgres/countries_dump_frag.sql:/docker-entrypoint-initdb.d/countries_dump_frag.sql
      - ./backups:/backups
    ports:
      - "5432:5432"
  backend:
    container_name: server
    build: ./server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - qdrant
    environment:
      - OPENAI_API_KEY=sk-...
      - DATABASE_URL=postgresql+asyncpg://postgres:root@db:5432/guess_country
      - QUIZ_MODEL=gpt-4o-mini
      - SECRET_KEY=...
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30   
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - COLLECTION_NAME=countries
      - EMBEDDING_MODEL=text-embedding-ada-002
      - EMBEDDING_SIZE=1536
      - EMAIL_USERNAME=jakub.melzacki@jmelzacki.com
      - NOREPLY_EMAIL=noreply@jmelzacki.com
      - EMAIL_PASSWORD=...
      - GOOGLE_CLIENT_ID=...
    volumes:
      - ./data:/usr/src/app/data
      - ./databases/qdrant/snapshots:/qdrant/snapshots
  frontend:
    container_name: client
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend

