"""Redesign question table

Revision ID: d55008ed8575
Revises: a62846f460bf
Create Date: 2024-09-17 06:15:02.241158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d55008ed8575"
down_revision: Union[str, None] = "a62846f460bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")

    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("day_id", sa.Integer(), nullable=True),
        sa.Column("context", sa.String(), nullable=True),
        sa.Column("original_question", sa.String(), nullable=False),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("answer", sa.Boolean(), nullable=True),
        sa.Column("explanation", sa.String(), nullable=False),
        sa.Column("asked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["day_countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
